### PR TITLE
support for DPT 3

### PR DESCRIPTION
**Pull request by matthewberryman**
I've done some work towards support for DPT3. I have done some local testing just running the code without any knx equipment while I wait on some to be returned to me with a DPT3 dimmer added. However, before I get to test on hardware, I thought I would submit a preliminary pull request so you can see the direction I've gone down and review that, before changes, testing, and then merge & close. Notably I've broken down the value into a control bit "c" (true/1 for up, false/0 for down) and then the 3 bit amount.
Some sample json payload you can inject:
```json
{"dstgad":"5/0/2","dpt":"3","value":{"c":"true","amount":"5"}}
```

### CODE REVIEW

**Comment by aborovsky** [comment]
@matthewberryman thx a lot for PR! We'll review it soon.

**Comment by ykornilov** [comment]
Matthew, good afternoon!
It is necessary to make changes to the code to make it work:

1.
value = ((value.c.toString () === 'true' || value.c.toString () === '1') << 4) |
replaced by
value = ((value.c.toString () === 'true' || value.c.toString () === '1') << 3) |

2.
buf [0] = value & 8;
replaced by
buf [0] = value & 15;

3.
if (! (value.c)) {
   throw 'Value up / down control missing';
...
It will raise an exception if the field "value.c" contains 0 or false (not "0" or "false")

We want to keep maintain the possibility of using our version (if the "value"  does not contain fields "value.c" and "value.amount")

If you want to add a change, fix, please node data-help in file knx.html

Thank you for your interest!

**Comment by matthewberryman** [comment]
1. Sorry, I had an off by one error in amount of shit.
2. Yes, the bitmask here should be all ones to preserve all the bits when casting, my bad.
3. I was too lazy in checking for existence of the control c, the new code now handles the case 0/false.

I have also updated the html with a description and example of dpt3; I also fixed a typo (wasn't critical but it was throwing out syntax highlighting in my editor).

I still don't have a dimmer to test this on actual hardware (arriving next week I hope).

**Comment by ykornilov** [comment]
For compatibility with the previous version, we propose to make such an option:
```
if (typeof(value.c) !== 'undefined' && value.c !== null && 
    typeof(value.amount) !== 'undefined' && value.amount !== null) {
            	if (value.amount <= 7) {
            		value = ((value.c.toString() === 'true' || value.c.toString() === '1') << 3) |
            		parseInt(value.amount) & 7;
            		buf = new Buffer(1);
            		buf[0] = value & 15;
            		value = buf;
            	} else {
            		throw 'Value step amount too big for DPT 3';
            	}
            } else if (!isNaN(parseInt(value))) {
            	buf = new Buffer(1);
            	buf[0] = parseInt(value) & 15;
            	value = buf;
            } else if (!Buffer.isBuffer(value)) {
            	throw 'Value is incorrect for DPT 3 (type of value should be Buffer or Value = 0..15 or Object with fields "value.c" = 0..1 and "value.amount" = 0..7)';
            }
```

**Comment by matthewberryman** [comment]
Good suggestions, have made those changes. My dimmer will arrive soon.

**Pull request merged**
